def test(exception):
    print(exception)